apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: ftccloud
spec:
  replicas: 10
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: harbor.test.myfaccloud-301.com/demogitops/simpleDemo:latest
        ports:
        - containerPort: 80