# values.yaml
replicaCount: 4

image:
  repository: harbor.test.myfaccloud-301.com/demogitops/simple-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
