# values.yaml
replicaCount: 3

image:
  repository: harbor.test.myfaccloud-301.com/fortinet/simple-app
  tag: 20241014-215207
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
